server:
  port: 8081
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///G:/ESTUDIO/Youtube/Luigi_Code/microservicios/git-config-server
          default-label: master